#docker build -t kafka1:latest ./docker/kafka
#jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=
version: "3.7"
services:
  kafka:
    image: kafka1:latest
    ports:
      - "2181:2181"
      - "9092:9092"
      - "9000:9000"
      - "8080:8080"
      - "8888:8888"
    volumes:
       - ./config:/opt/kafka_2.13-2.8.0/config
       - .:/mounted
    environment:
      - "SPARK_LOCAL_IP=spark-master"
